# Add your OpenAI API key here for cloud deployment
# Make sure to replace the placeholder with your actual API key
OPENAI_API_KEY = "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"
