# Add your OpenAI API key here for cloud deployment
OPENAI_API_KEY = "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"
